### PR TITLE
fix support for jscrollbar

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
I fixed the problem that the icons had on the buttons of the respective vertical and horizontal scrollbars

### CODE REVIEW

**Comment by atarw** [comment]
I'm going to be busy until after the weekend, but could you tell me what the problem with the icons on scrollbars was (just so I can review the changes better)

**Comment by vincenzopalazzo** [comment]
Of course, nothing complicated in the vertical and horizontal scrolls were visualized the same jbuttons with the same icons, so both in the vertical and horizontal that buttons were buttons with icons UP and down.

**Comment by atarw** [comment]
I did a bit of research and it turns out Java has a built in solution with `BasicArrowButton`, so I used that to fix that bug.

**Comment by vincenzopalazzo** [comment]
Fantastic, I did not know about this integrated function, in fact with the existence of this component my solution really becomes "old school".

**Pull request closed without merging**
