### PR TITLE
Fix for nested JTree view

### PR DESCRIPTION
**Pull request by mikera**
The JTree view did not seem to be laying out the children correctly in nested mode (i.e. a root node with children)

I traced this issue to having a "null" icon for leaf nodes, which causes the indent of the leaf nodes to be incorrect.

This PR fixes the issue by adding a small transparent ICON to use for leaf nodes.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Also @mikera, in this project there isn't the last version of code, you should be follower the developer project [vincenzopalazzo/material-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing/tree/development) in the development branch.

The developer branch is tester each week with and big project how [JMars](http://jmars.mars.asu.edu/) and with these tests, we can have the feedback to the last code.

I want say you this just if you have interesting to work with the last code of the project.

**Comment by mikera** [comment]
Hi @vincenzopalazzo happy to help out - seems like a good and useful project, I often want to create simple but good-looking GUIs in Swing.

Can you just clarify - you want new PRs to be sent against against the "development" branch suggested above, rather than the main "master" in this fork?

**Comment by vincenzopalazzo** [comment]
Hi @mikera,

> Hi @vincenzopalazzo happy to help out - seems like a good and useful project, I often want to create simple but good-looking GUIs in Swing.

Thanks 

>Can you just clarify - you want new PRs to be sent against against the "development" branch suggested above, rather than the main "master" in this fork?

Yes, if you want within future PR you can use the last version of code. After the testing, the stable version I will do push inside this branch.

For this PR I will push inside this master but in the future for me is more simple testing the code and noted the problem in the developer branch.

**Comment by mikera** [comment]
OK thanks. I will do any work on your development branch in future.

**Comment by vincenzopalazzo** [comment]
Hi @mikera, thanks you, if you complete this PR I will merge with the master

**Comment by vincenzopalazzo** [comment]
This PR was merged inside the correct fork and now are available on version 1.1.1.

**Pull request closed without merging**
