### PR TITLE
init partial fix at issue #60

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
## Init effect mouseover and change cursor when mouse is on Jbutton

let me know if you like it :) if yes I try to add this effect to other component

557b2o

## Now are in plus two  key in the UIDefoults, this
`table.put("Button.mouseHoverColor", MaterialColors.GRAY_500);
  table.put("Button.mouseHoverEnable", true);`

### CODE REVIEW

**Comment by atarw** [comment]
Just wondering why is there an `EffectButton` class? Is it possible to just call `MaterialUIMovement.add()` directly when initializing the component?

**Comment by vincenzopalazzo** [comment]
you're right, I got distracted I created the sclasse effect button because I wanted to generalize the color but then I added the key to the map of UIDefoult, I remove the class in the next few hours, I'm sorry

**Comment by vincenzopalazzo** [comment]
Hello @atarw Adding MaterialUIMuviment to the creation would lose all the possible colors set with setBackground in the application that uses the look and feel, in fact in the demo if you set that action in the installUI the component at the end of the action of MaterialUIMovement takes the background color that is set to inside of UIDefoult so as to lose the color modified by the application side.

I do not know if I could explain, forgive my terrible English but I have to resort to google translator to explain complex thoughts :)

**Comment by vincenzopalazzo** [comment]
Hello @atarw,
I thought about it and the solution could be undertaken in some other way, in the next few days I try to solve the problem.

Sorry if we are making "noise" I hope not to bother you in your exams :)

**Pull request closed without merging**
