### PR TITLE
Create version 1.0 BETA

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
HI @atarw, this is my work, I hope it like you 

**Bug Fixed**
- Fixed issue #35
- Fixed issue #23
- Initi a DEMO [Swing Set](https://github.com/vincenzopalazzo/setSwing3)
- Fixed issue atarw#81
- Fixed issue atarw#80
- Fixed issue atarw#77
- [NullPointer into JTextField](https://github.com/vincenzopalazzo/material-ui-swing/issues/24)
- [Keyborad actions list](https://github.com/vincenzopalazzo/material-ui-swing/issues/29)
- [Removed arrow to Jscrollbar](https://github.com/vincenzopalazzo/material-ui-swing/issues/31)
- [Default action JOptionPane](https://github.com/vincenzopalazzo/material-ui-swing/issues/20)
- Fixed button focusable look
- Added support JList
- Graphic alignment JTextField and JPasswordField
- Init refactoring to code

**Look new Component supported**

**JList**
Selection_010

**New Color**
*Screenshot*
Selection_014

*Constant name*
```
Color DARKLY_STRONG_BLUE
Color DARKLY_BLUE 
Color COSMO_STRONG_BLUE
Color COSMO_BLUE
Color COSMO_LIGTH_BLUE
Color DARKLY_RED 
Color COSMO_RED
Color COSMO_LIGHT_RED
Color COSMO_PURPLE
Color COSMO_LIGHT_PURPLE
Color DARKLY_ORANGE
Color COSMO_ORANGE
Color COSMO_LIGHT_ORANGE
Color DARKLY_STRONG_GREEN
Color DARKLY_GREEN 
Color COSMO_GREEN 
Color COSMO_LIGHT_GREEN
Color COSMO_LIGTH_GRAY
Color COSMO_MEDIUM_GRAY
Color COSMO_STRONG_GRAY
Color COSMO_DARK_GRAY
Color DARKLY_GRAY
Color COSMO_BLACK
```

**Screen demo *swing_set* whit material-ui-swing**
Selection_015
Selection_016
Selection_017
Selection_018
Gif combo box

**ALPHA SKILL**
I'm also introducing changes to JDialog and JTabbledPane but I didn't want to bring these into your project yet because they are in alpha version and may malfunction, but you can watch the effect here, let me know what you think
https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V1.0_Beta

Good day and Happy Easter :)

### CODE REVIEW

**Comment by NhocKun** [comment]
Nice work pro. How can i using JOptionPanel with out undecorated :D

**Comment by lilili87222** [comment]
frame
file


1.frame title bar is too large
2.file chooser ,file name input no border is ugly

**Comment by vincenzopalazzo** [comment]
> Nice work pro. How can i using JOptionPanel with out undecorated :D

Thanks so much, @NhocKun you can use a JOptionPane not decorated whit this code 
`JDialog.setDefaultLookAndFeelDecorated(true);` before you set a look and feel of the UIManager

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222, Thanks for your help you for creating a better look and feel.

> 1.frame title bar is too large

The `JFrame.setDefaultLookAndFeelDecorated(true);` not supported for moment, sorry

> 2.file chooser ,file name input no border is ugly

Yes, this is the problem, I want re-project the JTextFieldUI for create this [effect](https://material.io/design/components/text-fields.html) but I need time to do this, and in the coming months I don't have this time, maybe I try to at least try to change the background color

I also changed the fonts updated, so that you can still see the squares with Noto sans?

**Comment by vincenzopalazzo** [comment]
@lilili87222, I have proposed this solution for the moment 
Selection_024
Now is more cool, right? :)

**Pull request merged**
